name: 部署文档

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-main:
    runs-on: ubuntu-latest
    steps:
      # clone 该仓库的源码到工作流中
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # "最近更新时间"等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - name: 安装 pnpm
        uses: pnpm/action-setup@v4


      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      
      - name: 安装依赖
        run: pnpm install --frozen-lockfile

      - name: 构建文档
        run: pnpm run docs:build

      - name: 部署文档
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          FOLDER: docs/.vuepress/dist
          BRANCH: gh-pages
